name: Generate Changelog

# on:
#   push:
#     branches:
#       - '*'

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore
      - name: Output Changelog
        id: output_changelog
        run: TAGCONTENT="${{ steps.changelog.outputs.changelog }}";TAGCONTENT=$(echo "$TAGCONTENT" | grep '#');CHANGELOG=$(cat CHANGELOG.md);CHANGELOG=$(echo "$CHANGELOG" | sed -e "s/# Changelog/# Changelog\n${TAGCONTENT}/");echo "$CHANGELOG" > CHANGELOG.md
