name: Generate Changelog

on:
  push:
    branches:
      - '*'

jobs:
  update_changelog:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      - name: Generate Changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1.0.4
        with:
          token: ${{ secrets.SEEDER_GITHUB_TOKEN }}
          exclude_types: other,doc,chore
        env:
          GITHUB_TOKEN: ${{ secrets.SEEDER_GITHUB_TOKEN }}
