name: Generate Changelog

on:
  push:
    branches:
      - '*'

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore